### ISSUE TITLE
ENV variable with default URL

### ISSUE THREAD

**Issue by rschellhorn** [geowarin/tarec#37]
I'm just trying this tool. It's a great clean-up over my custom webpack config etc.

However I'm running into the following issue. In the readme there is an example describing the environment variables with an URL as default value. This isn't actually working, due to the way variables are split by ':'.

The default value is interpreted as 'http', instead of the full url

**Comment by geowarin** [comment]
Whoops looks like my last refactor is responsible for this.
Fix is on the way. Thanks for reporting!

**Comment by geowarin** [comment]
This should be fixed in v1.4.1.

**Comment by rschellhorn** [comment]
Thanks a lot! Works like a charm.
