### ISSUE TITLE
Proxies does not support upgrade for Websockets

### ISSUE THREAD

**Issue by cedbossneo** [geowarin/tarec#4]
Some frameworks needs to do a first http request and then upgrade the request to Websocket.

It doesn't work with the current implementation so SockJS / Primus... always throw an error and switch to polling.

#2 fixes this

**Comment by geowarin** [comment]
Could you please try pointing to the master branch and see if it fixes your problem ?

**Comment by cedbossneo** [comment]
Works like a charm.
LGTM

2016-07-03 20:18 GMT+02:00 Geoffroy Warin <notifications@github.com>:
